name: Build my QMK configuration

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build-qmk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: sofle_choc
          keymap: cheyrich
          controller: promicro_rp2040
          local-keymap-path: keymaps/sofle_choc/cheyrich
          output-dir: qmk-firmware

      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: qmk-firmware
